services:
  website:
    image: ghcr.io/calfur/pannenstreifen-website:latest
    platform: linux/amd64
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
