name: Build website and deploy with Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./App/package-lock.json

      - name: Run npm commands
        working-directory: App
        run: |
          npm ci
          npm run build

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/calfur/pannenstreifen-website:${{ github.sha }}
            ghcr.io/calfur/pannenstreifen-website:latest
          build-args: |
            VERSION=alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8

  deploy-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: SSH, docker-compose pull, docker-compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/docker-projects/pannenstreifen
            docker-compose pull && docker-compose up -d --force-recreate
