# Simple workflow for deploying static content to GitHub Pages
name: Build Typescript and SCSS files with Parcel and upload to FTP
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
          
      - name: ftp-action
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: www533.your-server.de
          user: pannenp_0
          password: ${{ secrets.FTP_PASSWORD }}
          forceSsl: false
          localDir: App/dist
          remoteDir: public_html
