name: Build website and deploy with Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./App/package-lock.json

      - name: Run npm commands
        working-directory: App
        run: |
          npm ci
          npm run build

      - name: Build Docker image
        run: docker build -t pannenstreifen-website .

      - name: Upload Docker image to server and restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Configure bash to exit on error
            set -euxo pipefail

            # Ensure the Docker network exists
            docker network inspect website_net >/dev/null 2>&1 || docker network create website_net

            # Prepare to receive the Docker image
            mkdir -p /tmp/docker-load
            cd /tmp/docker-load

            # Listen for incoming Docker image data
            cat > pannenstreifen-website.tar

            # Load the Docker image
            docker load < pannenstreifen-website.tar

            # Remove old container if it exists
            docker stop pannenstreifen-website || true
            docker rm pannenstreifen-website || true

            # Run new container within the network
            docker run -d --name pannenstreifen-website --net website_net pannenstreifen-website

            # Clean up
            rm -rf /tmp/docker-load
