name: Build website and deploy with Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./App/package-lock.json

      - name: Run npm commands
        working-directory: App
        run: |
          npm ci
          npm run build

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/calfur/pannenstreifen-website:${{ env.IMAGE_VERSION }}
            ghcr.io/calfur/pannenstreifen-website:latest
          build-args: |
            NGINX_VERSION=alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8

  trigger-deployment:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger image update in Calfur/calfur-dev
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_ACTIONS_TRIGGER }}
          repository: Calfur/calfur-dev
          event-type: new-pannenstreifen-website-image
          client-payload: '{"image_version": "${{ env.IMAGE_VERSION }}"}'
